import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, theme } from "antd";
import Link from "next/link";
import GlobalContextWraper from "@/context/maincontext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-neutral-950`}
      >
        <AntdRegistry>
          <ConfigProvider
            theme={{
              algorithm: [theme.darkAlgorithm, theme.compactAlgorithm],
              token: {
                colorPrimary: "#1677ff",
                borderRadius: 10,
              },
            }}
          >
            <div className="flex justify-center align-middle gap-5 absolute top-0 left-1">
              <Link href="/">Home</Link>
              <Link href="/login">Login</Link>
              <Link href="/register">Register</Link>
              <Link href="/dashboard">Dashboard</Link>
            </div>
            <GlobalContextWraper>
              <div className="box-border min-h-screen">{children}</div>
            </GlobalContextWraper>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
